export const CHANGE_SEARCH_VIDEO_FIELD = 'CHANGE_SEARCH_VIDEO_FIELD';
export const REQUEST_VIDEO_PENDING = 'REQUEST_VIDEO_PENDING';
export const REQUEST_VIDEO_SUCCESS = 'REQUEST_VIDEO_SUCCESS';
export const REQUEST_VIDEO_FAILED = 'REQUEST_VIDEO_FAILED';